language: node_js
node_js:
  - "5"
notifications:
  email:
    - ovidiu.bute@gmail.com
script: 
  - npm test
before_install:
  - openssl aes-256-cbc -K $encrypted_beedcc9aa06e_key -iv $encrypted_beedcc9aa06e_iv -in deploy-key.enc -out deploy-key -d
  - chmod 0600 deploy-key
after_success:
  - ssh-keyscan -H 159.203.152.181
  - pm2 deploy ecosystem.json production
